// app/src/main/java/com/hul0/mindflow/model/MoodEntry.kt
package com.hul0.mindflow.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single mood entry in the database.
 * @param id The unique identifier for the entry. It's auto-generated by the database,
 * so we provide a default value of 0 for new entries that haven't been inserted yet.
 * @param mood The emoji representing the user's mood.
 * @param timestamp The time the entry was created.
 * @param note An optional note the user can add to their mood entry.
 */
@Entity(tableName = "mood_entries")
data class MoodEntry(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val mood: String,
    val timestamp: Long,
    val note: String? = null
)
